import './App.css'
import DataProvider from './components/data-provider'
import StepViewer from './components/step-viewer/step-viewer'
import StringArtForm from './components/string-art-form/string-art-form'
import { LOCAL_STORAGE_KEY_STEP } from './data/helper'

function App() {
  const savedStep = localStorage.getItem(LOCAL_STORAGE_KEY_STEP);
  const step = savedStep ? parseInt(savedStep) : 0;

  return (
    <DataProvider>
      <header>
        <h1>String art stepper</h1>
        <StringArtForm />
      </header>
      <main>
        <StepViewer step={step}></StepViewer>
      </main>
      <footer>
        <p>The file that you need to upload must to be generated by the <a href="https://www.stringartgenerator.app/">String Art generator</a></p>
      </footer>
    </DataProvider>
  )
}

export default App
