import './App.css'
import DataProvider from './components/data-provider'
import Toolbar from './components/toolbar/toolbar'
import MainPage from './pages/main-page/main-page'

function App() {
  return (
    <>
      <header>
        <h1>String Art Stepper</h1>
        <h3>An assistent for make your string art more easy</h3>
      </header>
      <DataProvider>
        <Toolbar />
        <main>
          <MainPage></MainPage>
        </main>
      </DataProvider>
      <footer>
        <p>The file that you need to upload must to be generated by the <a href="https://www.stringartgenerator.app/">String Art generator</a></p>
        <p>Developed by AnesCDev</p>
      </footer>
    </>
  )
}

export default App
