import './App.css'
import DataProvider from './components/data-provider'
import { fetchSavedStep } from './components/step-viewer/helper'
import StepViewer from './components/step-viewer/step-viewer'
import StringArtForm from './components/string-art-form/string-art-form'

function App() {
  const step = fetchSavedStep()

  return (
    <DataProvider>
      <header>
        <h1>String art stepper</h1>
        <StringArtForm />
      </header>
      <main>
        <StepViewer step={step}></StepViewer>
      </main>
      <footer>
        <p>The file that you need to upload must to be generated by the <a href="https://www.stringartgenerator.app/">String Art generator</a></p>
      </footer>
    </DataProvider>
  )
}

export default App
